site_name: pyxtb

nav:
  - Api: index.md
  - Types: types.md

plugins: 
  - search
  - privacy
  - badges
  - mkdocstrings:
      handlers:
        python:
          options:
            heading_level: 2
            parameter_headings: true
            signature_crossrefs: true
            show_root_toc_entry: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            members_order: alphabetical
            separate_signature: true
            show_signature_annotations: true
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            allow_inspection: true
            show_labels: false
            relative_crossrefs: true
            filters: 
              - "!^_"
              - "!^T$"
              - "^__"
repo_name: MichalKarol/pyxtb
repo_url: https://github.com/MichalKarol/pyxtb

theme:
  name: material
  font:
    text: Roboto
  features:
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.pl/@mkarol
      name: mkarol on Mastodon
    - icon: fontawesome/brands/github
      link: https://github.com/MichalKarol
      name: MichalKarol on Github

    
copyright: Copyright &copy; 2024 Michał Karol <michal.p.karol@gmail.com>

validation:
  omitted_files: warn
  absolute_links: warn  
  unrecognized_links: warn
  anchors: warn  